### ISSUE TITLE
Potential dependency conflicts between bigga and fabric

### ISSUE THREAD

**Issue by NeolithEra** [reckonsys/bigga#2]
Hi, as shown in the following full dependency graph of  **_bigga_**, **_bigga_** requires **_fabric *_** ， while the installed version of **_patchwork_**(1.0.1) requires _**fabric  >=2.0,<3.0**_.

According to Pip's _“first found wins”_ installation strategy, _**fabric 2.5.0**_ is the actually installed version.  

Although the first found package version _**fabric 2.5.0**_ just satisfies the later dependency constraint （_**fabric  >=2.0,<3.0**_), it will lead to a build failure once developers release a newer version of fabric.

### Dependency tree--------
```
bigga - 0.2.1
| +- fabric(install version:2.5.0 version range:*)
| +- invoke(install version:1.3.0 version range:*)
| +- patchwork(install version:1.0.1 version range:*)
| | +- fabric(install version:2.5.0 version range:>=2.0,<3.0) 
```

Thanks for your attention.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution

1.	Fix your direct dependencies to be **_fabric <3.0_**.
2.	Ask your upstream project **_patchwork_** to lose the version range of **_fabric_** to be **_>=2.0_**.

@dhilipsiva Which solution do you prefer, 1 or 2?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by dhilipsiva** [comment]
Hey @NeolithEra , Apologies on the very late reply. Bigga moved away from fabric. We are now now completely docker-based.

**Comment by dhilipsiva** [comment]
But I really appreciate you taking the effort :)
